services:
  - type: web
    name: nutrishita
    env: node
    plan: free
    buildCommand: NPM_CONFIG_PRODUCTION=false npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true
